services:
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    # entrypoint: /app/docker-entrypoint.sh
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    ports:
      - "8000:8000"