name: Deploy to Amazon ECS

on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - main

env:
  AWS_REGION: ca-central-1                    # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: 988178274635.dkr.ecr.ca-central-1.amazonaws.com/gng5300-simple-instagram-be      
                                              # set this to your Amazon ECR repository name
  ECS_SERVICE: gng-5300-simple-instagram-be-service   # set this to your Amazon ECS service name
  ECS_CLUSTER: gng-5300-simple-instagram-cluster   # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: gng-5300-simple-instagram-be-task
                                              # set this to the path to your Amazon ECS task definition
                                              # file, e.g. .aws/task-definition.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ECS_SECRET }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        cd backend
        docker build -t $ECR_REPOSITORY .
        docker push $ECR_REPOSITORY:latest
        echo "::set-output name=image::$ECR_REPOSITORY:latest"

    - name: Deploy Amazon ECS task definition
      id: deploy-task
      run: |
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
